[package]
name = "voracious_code_storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
uuid = { version = "1.4.1", features = ["v4"] }
