[package]
edition = "2021"
name = "line_reversal_async"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console-subscriber = "0.1.8"
tokio = {version = "1.22.0", features = ["full"]}
